# This will add the project root and the folder protoapp, containing the code, to the PYTHONPATH
# when running pytest
[pytest]
pythonpath = protoapp .
markers = 
    integration: marks tests as integration